sonar.projectKey=NOEM_AK
sonar.projectName=NOTE_TAKER
sonar.host.url=http://localhost:9000

sonar.sources=Frontend/react-app/src,Backend/node-app

sonar.exclusions=**/node_modules/**,**/.env,**/.env.*,**/dist/**,**/build/**,**/coverage/**,**/.git/**

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=Frontend/react-app/coverage/lcov.info,Backend/node-app/coverage/lcov.info