sonar.projectKey=NOEM_AK
sonar.projectName=NOTE_TAKER
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.exclusions=**/node_modules/**,**/.env,**/.env.*,**/dist/**,**/build/**,**/coverage/**,**/.git/**
sonar.sourceEncoding=UTF-8